
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const Assessments = lazy(() => import("./pages/Assessments.tsx"));
const Badges = lazy(() => import("./pages/Badges.tsx"));
const Jobs = lazy(() => import("./pages/Jobs.tsx"));
const Skills = lazy(() => import("./pages/Skills.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/assessments", element: <UserGuard><Assessments /></UserGuard>},
	{ path: "/badges", element: <UserGuard><Badges /></UserGuard>},
	{ path: "/jobs", element: <UserGuard><Jobs /></UserGuard>},
	{ path: "/skills", element: <UserGuard><Skills /></UserGuard>},

];
